### ISSUE TITLE
issue test 001

### ISSUE THREAD

**Issue by eleutheria80** [kmu-crc/OpenDesign-2017.08#1]
- Title : first issue
- member : opensrcdesign-admin
- contents : login scene

@opensrcdesign-admin check this issue.

**Comment by opensrcdesign-admin** [comment]
로그인 씬 어떤거 말씀하시는지요? 좀 더 자세히 설명해주시면 감사하겠습니다 :)

**Comment by eleutheria80** [comment]
@opensrcdesign-admin JIRA 대신 Issue를 사용할 수 있을지 테스트로 작성 해 본 겁니다. 회의 때 논의하도록 하겠습니다.
